import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LogsContext, { Log } from '../context/LogsContext/LogsContext'
import { useState } from 'react'
import FileUpload from '../components/FileUpload'
import LogsDisplay from '../components/LogsDisplay'

const Home: NextPage = () => {
  const [logs, setLogs] = useState<Array<Log>>([])

  return (
    <LogsContext.Provider value={{ logs, setLogs }}>
      <div className={styles.container}>
        <Head>
          <title>Log File Interpreter</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Log File Viewer
          </h1>
          <FileUpload />
          <LogsDisplay />
        </main>
      </div>
    </LogsContext.Provider>
  )
}

export default Home
